version: '3'
services:
  accelerate:
      image: 'ghcr.io/haouarihk/prisma-accelerate-local:latest'
      restart: unless-stopped
      ports:
        - 4000:4000
      stop_signal: SIGKILL
      network_mode: host
      environment:
        - PORT=4000
        - HOST=localhost
        - USE_ELYSIA=1