version: '3'
services:
  accelerate:
      build:
        context: .
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
        - 4000:4000
      stop_signal: SIGKILL
      network_mode: host
      environment:
        - PORT=4000
        - HOST=localhost
        - USE_ELYSIA=1
        - PRISMA_TRACE_ENGINE_CLIENT=0
        - PRISMA_TELEMETRY_INFORMATION_DISABLED=1